version: '3.8'

networks:
  devops-network:
    driver: bridge
    name: devops-network



volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonar_postgres_data:
  grafana_data:
  zap_data:

services:
  pet_clinic:
    build:
      context: ..
      target: pet_clinic
    container_name: pet_clinic-pet_clinic
    ports:
      8080:
    networks:
      - devops-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./spring-petclinic:/workspace/spring-petclinic
    networks:
      - devops-network
    environment:
      - JAVA_OPTS=-Duser.timezone=America/New_York
    user: root  

  # i think we need a separate postgre for sonar cube but lmk if its right
  sonar-postgres:
    image: postgres:13
    container_name: sonar-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonar_postgres_data:/var/lib/postgresql/data
    networks:
      - devops-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonar-postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - devops-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - devops-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - devops-network

  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    ports:
      - "8090:8090"
    volumes:
      - zap_data:/zap/wrk
    command: zap-webswing.sh
    networks:
      - devops-network