#todo: set up code for the prometheus

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is 1m.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. Default is 1m.

  scrape_configs:
    - job_name: 'spring-pet-clinic'
      static_configs:
    - targets: ['localhost:8080']