global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'spring-clinic-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'jenkins'
    scrape_interval: 5s
    metrics_path: /prometheus
    static_configs:
      - targets: ['jenkins:8080']
